### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by tloth** [FAC-Sixteen/square-circle#29]
Daily to dos and to dos for the day after :monkey:

**Comment by tloth** [comment]
## Monday 03/06

- [x] add user story as issues (AnnaT)
- [ ] create process guide (AnnaT)
- [x] tell Charlie who's doing what (AnnaB)
- [ ] design guide (Rohan)
- [x] set up figma (Rohan)
- [x] brainstorm layout (all)

        * big logo homepage
            * scroll down
            * mission statement
            * some companies as example
        * employers
            * values (pledges)
            * company tiles
            * with icons for pledges
            * onclick open up modal with more info
        * contact form: get in touch
- [x] research whether we can integrate our website with SquareSpace/etc
- [x] write to Kath & Keir
    - [x] roles
    - [x] where to comment
    - [x] SEND US CONTENT ASAP PLEASE :)

### for tomorrow
* get back to Kath about SquareSpace

**Comment by tloth** [comment]
## Tuesday 04/06

- [x] get back to Kath and Keir about SquareSpace
- [x] FIGMA
- [ ] look into Airtable

**Comment by tloth** [comment]
## Wednesday 05/06

Morning:
- [x] schedule user testing with K&K
- [x] change figma according to feedback
- [x] hungarian figma

Afternoon:
- [x] Airtable learning - tech spike
    * Suggestion: can we open a shared Airtable notes hackmd? :> :3 >:)

### for tomorrow
* put together user testing list/questionnaire for Kath&Keir for Friday morning (send on Thurs!)
* Anna T: add milestone issue "Project Setup" (on whiteboard! ask Joe if questions) (notes in SC hackmd)
* Rohan: update Style Guide! (in style.js?? AND in issue #3 plz)

**Comment by tloth** [comment]
## Thursday Week 1 06/06
- [x] send Kath user testing script
- [x] change figma according to Kath's feedback
- [ ] what are milestones?? --> project setup
- [x] discuss process
- [x] update style guide (Rohan)
- [ ] file structure & create react app (Anna B & all)
    - [ ] set up linter (AnnaB)
- [ ] sprint planning https://github.com/foundersandcoders/master-reference/blob/master/coursebook/weeks-10-12/build-sprint/preparing-for-build-sprint.md
- [ ] set up Airtable so that we can show them how it works tomorrow
    - [ ] + description
    - [ ] + logo!!!

**Comment by tloth** [comment]
## Monday Week 2 10/06

### for tomorrow

- [ ] sprint planning
- [ ] finish common components
- [ ] finish landing page and FAQ pages

**Comment by tloth** [comment]
## Tuesday Week 2 11/06
- [ ] sprint planning
- [ ] finish common components with tests

if time:
- [ ] finish landing page
- [ ] finish FAQ pages

**Comment by tloth** [comment]
## Wednesday Week 2 12/06

- [ ] update figma and screenshots in issues (Anna T)
- [ ] finish footer and button (Burhan and Anna T)
- [ ] finish mobile navigation with animated slide-in (Anna B and Rohan)
- [ ] start work on landing page
- [ ] start work on FAQ pages

**Comment by tloth** [comment]
Thursday Week 2 13/06

- [ ] Employers FAQ page
- [ ] Contact page
- [ ] Criteria page
- [ ] Jobs page

**Comment by tloth** [comment]
## Friday Week 2 14/06

- [ ] finish Contact page
- [ ] finish Criteria page
- [ ] do Jobs page
- [ ] write tests

**Comment by tloth** [comment]
## Monday Week 3 17/06

- [ ] start readme

**Comment by tloth** [comment]
# WEEK 3
To get done by the end of Thursday!

- [ ] finish pages: Jobs(!!!), add functionality
- [ ] connect Airtable
- [ ] create modals
- [ ] form: send email to SC and to sender
- [ ] add background (animated?)
- [ ] make sure app is fully responsive
- [ ] check accessibility
- [ ] 

:frog:

**Comment by tloth** [comment]
## Tuesday Week 3 18/06/19

- [ ] set up netlify functions!!!
- [ ] finish Jobs page!!!
- [ ] create modal onclick!!!
- [ ] have Airtable ready

**Comment by tloth** [comment]
## Wednesday Week 3 19/06/19

- [ ] small fixes #2 #93 
- [ ] finish modal onclick
- [ ] connect Airtable
- [ ] test functionality

- [ ] add background image

**Comment by tloth** [comment]
## Thursday Week 3 20/06/19

- [ ] fix style
- [ ] check both mobile and desktop styling is adequate
- [ ] add background image
- [ ] readme
- [ ] script user testing
- [ ] create documentation for handover
- [ ] tests

**Comment by tloth** [comment]
## Friday Week 3 21/06/19

- [ ] commit readme (Anna B)
- [ ] prep presentation
- [ ] prep what to say at handover

**Comment by tloth** [comment]
## Handover and Post-Handover :heart: bugs :heart:

- [ ] write documentation with
   - [ ] airtable - how to add/delete/edit employer/criteria
   - [ ] netlify - how to change email address & force deploy
- [ ] add links to icons in footer
- [ ] take out second drop down in Get in touch page --> revisit email function, too
- [ ] in ‘Thank You. Your message has been received’ please make the ‘y’ on the
you lower case
- [ ] styling
   - [ ] when you load a new page by clicking through a link e.g from ‘see
employers, to jobs page, it doesn’t load at the head it loads down the
page.  Please can it automatically load with the header at the top of the
page.
   - [ ] when you click on the icons of London living wage etc, it doesn’t fit in
the box or the page (see pic). please can text in pop up be smaller so it
all fits
   - [ ] can the logos of the pledges please be bigger on the criteria page
   - [ ] titles of employers should be centred
- [ ] logo in footer on internet explorer cut off???
- [ ] modals: make accessible (Reach UI)
