### ISSUE TITLE
As an employer, ...

### ISSUE THREAD

**Issue by tloth** [FAC-Sixteen/square-circle#35]
## :whale: As an employer,
- [ ] I want to understand what SC's mission and criteria are #
- [ ] I want to know how to become a part of SC #
- [ ] I want to be able to contact SC to ask to get on the jobs board (via email) #
