### ISSUE TITLE
As the admin, ...

### ISSUE THREAD

**Issue by tloth** [FAC-Sixteen/square-circle#36]
## :beetle: As the admin,
- [ ] I want to be able to easily navigate on the website #
- [ ] I want to be able to add new employers to the database #
- [ ] I want to see the changes I make in the database automatically update on the website #
- [ ] I want to receive messages from the website via email #
- [ ] I want to know how to change the contact email address in the form #
- [ ] I want to somehow integrate a blog section (stretch) #
- [ ] I want to include my instagram posts on the website (stretch) #
