### ISSUE TITLE
(1) Landing page

### ISSUE THREAD

**Issue by tloth** [FAC-Sixteen/square-circle#39]
![landing](https://i.imgur.com/bKvns53.png)

- [x] header saying 'Jobs Board'
- [x] burger icon on left --> menu
- [x] logo
- [x] content
- [x] buttons:
   - [x] SEE EMPLOYERS
   - [x] SEE OUR CRITERIA
- [ ] white background with grey shapes (moving?)
- [x] footer with email linked to (CONTACT) page
