### ISSUE TITLE
(2/1) JOBS page

### ISSUE THREAD

**Issue by tloth** [FAC-Sixteen/square-circle#40]
![jobs](https://i.imgur.com/l4jO7W1.png)
(+ footer)

- [x] header saying 'Jobs'
- [x] 'Employers who meet our criteria' as a pinned heading under the banner
- [x] burger icon on left --> menu
- [x] employer tiles
   - [x] logo
   - [x] name
   - [x] description
   - [x] pledges
   - [x] 'SEE OPEN POSITIONS' button linking to employer's careers page
- [x] tile populated from Airtable #41
- [x] white background with grey shapes (moving?)
- [x] footer with email linked to (CONTACT) page
