### ISSUE TITLE
(3/1) Criteria page

### ISSUE THREAD

**Issue by tloth** [FAC-Sixteen/square-circle#42]
![criteria1](https://i.imgur.com/KukljT7.png)
![criteria2](https://i.imgur.com/Xy7fLTf.png)

- [x] header saying 'Criteria'
- [x] burger icon on left --> menu
- [x] Content
- [x] Living Wage Employer logo
   - [ ] pop up window on click with #
      - [ ] description
      - [ ] link to website
- [x] logos of pledges
   - [ ] pop up window on click with #
      - [ ] description
      - [ ] link to website
- [x] Applied logo
   - [ ] pop up window on click with #43
      - [ ] description
      - [ ] link to website
- [x] contact us Content
- [ ] white background with grey shapes (moving?)
- [x] footer with email linked to (CONTACT) page
