### ISSUE TITLE
(4) Get in Touch page

### ISSUE THREAD

**Issue by tloth** [FAC-Sixteen/square-circle#44]
![getintouch](https://i.imgur.com/7a3EOrw.png)
![getintouch-options](https://i.imgur.com/531n7al.png)
![getintouch-confirmation](https://i.imgur.com/VvUYNfu.png)

- [x] header saying 'Get in touch'
- [x] burger icon on left --> menu
- [x] form
   - [x] 2 drop-downs
   - [x] name: input type=text
   - [x] email: input type=email / regex
   - [x] message: text area
   - [x] checkbox
   - [x] SEND button
   - [ ] protect from script injections!
- [x] on submit: message of confirmation
- [ ] white background with grey shapes (moving?)
- [x] footer with email linked to (CONTACT) page(?)
