### ISSUE TITLE
(5) Applicant FAQs

### ISSUE THREAD

**Issue by tloth** [FAC-Sixteen/square-circle#45]
![applFAQ1](https://i.imgur.com/3dnwj8S.png)
![applFAQ2](https://i.imgur.com/2m3dTBV.png)
![applFAQ3](https://i.imgur.com/rfYrAtf.png)

- [x] header saying 'Applicant FAQs'
- [x] burger icon on right --> menu
- [x] list of FAQs linking to answers below
- [x] separator between questions and answers
- [ ] white background with grey shapes (moving?)
- [x] footer with email linked to (CONTACT) page
