### ISSUE TITLE
(6) Employer FAQs

### ISSUE THREAD

**Issue by tloth** [FAC-Sixteen/square-circle#46]
![empl1](https://i.imgur.com/G43cgEX.png)
![empl2](https://i.imgur.com/shG2sEx.png)

- [x] header saying 'Employer FAQs'
- [x] burger icon on left --> menu
- [x] list of FAQs linking to answers below
- [x] separator between questions and answers
- [ ] white background with grey shapes (moving?)
- [x] footer with email linked to (CONTACT) page
